# Copyright Sonatype, Inc., 2022, All Rights Reserved.
#
# You should not use Dynamic Volume Provisioning as it will cause scheduling problems if AKS provisions the Nexus Repository pod and the volume in different AZs. 
# The volume used must be the local volume attached as illustrated in the sample persistent volume YAML file. 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: nexus-repo-mgr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: <size> # E.g. 100Gi
