apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: nexus-repo-mgr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: <size> # E.g. 100Gi
