# Copyright Sonatype, Inc., 2022, All Rights Reserved.
#
# Note: This YAML file is just an example and cannot be used as-is. 
# You must fill it out with the appropriate information for your deployment to be able to use it.

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: nexus-repo-mgr
  name: nxrm-nexus-license-secret
spec:
  provider: azure
  secretObjects:
  - data:
    - key: db-password
      objectName: db-password
    - key: db-user
      objectName: db-user
    - key: db-host
      objectName: db-host
    - key: db-port
      objectName: db-port
    secretName: db-secret
    type: Opaque
  - data:
    - key: nxrm-admin-user
      objectName: nxrm-admin-user
    secretName: nxrm-secret
    type: Opaque
  parameters:
    keyvaultName: nexus-kv
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<client id>" # The clientId of the addon-created managed identity (see https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)
    objects: |
      array:
        - |
          objectName: nxrm-license
          objectType: secret
          objectEncoding: base64
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-port
          objectType: secret
        - |
          objectName: nxrm-admin-user
          objectType: secret
   
    tenantId: <tenant_id> # the tenant ID containing the Azure Key Vault instance (value of your key vault's 'Directory ID' in Azure portal.)
