# Copyright Sonatype, Inc., 2022, All Rights Reserved.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: nexus-repo-mgr
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
