# Copyright Sonatype, Inc., 2022, All Rights Reserved.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-blobstorage-claim
  namespace: nxrm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-blobstorage
  resources:
    requests:
      storage: <size>
