# Copyright Sonatype, Inc., 2022, All Rights Reserved.
#
# Note: This YAML file is just an example and cannot be used as-is.
# You must fill it out with the appropriate information for your deployment to be able to use it.

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: nxrm-nexus-27385
  name: nxrm-nexus-27385-nxrm-secret
spec:
  provider: aws
  secretObjects:
    - data:
        - key: db-user
          objectName: nxrm-db-user
        - key: db-password
          objectName: nxrm-db-password
        - key: db-host
          objectName: nxrm-db-host
      secretName: nxrm-db-secret
      type: Opaque
    - data:
        - key: nxrm-admin-user
          objectName: admin-nxrm-user
      secretName: nxrm-secret
      type: Opaque
  parameters:
    objects:  |
      - objectName: "arn:aws:secretsmanager:<region>:<account id>:secret:nxrm-license.lic-abcdef"
        objectAlias: nxrm-license.lic
      - objectName: "arn:aws:secretsmanager:<region>:<account id>:secret:nxrm-rds-cred-nexus-abcdef"
        jmesPath:
          - path: "username"
            objectAlias: "nxrm-db-user"
          - path: "password"
            objectAlias: "nxrm-db-password"
          - path: "host"
            objectAlias: "nxrm-db-host"
      - objectName: "arn:aws:secretsmanager:<region>:<account id>:secret:nxrm-admin-cred-nexus-abcdef"
        jmesPath:
         - path: "nxrmuser"
           objectAlias: "admin-nxrm-user"
